sudo: required
services:
  - docker

before_install:
  - docker build -t avolpe89/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true avolpe89/react-test npm test
  
after_success:
  - docker build -t avolpe89/multi-client ./client
  - docker build -t avolpe89/multi-nginx ./nginx
  - docker build -t avolpe89/multi-server ./server
  - docker build -t avolpe89/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to Docker Hub
  - docker push avolpe89/multi-client
  - docker push avolpe89/multi-nginx
  - docker push avolpe89/multi-server
  - docker push avolpe89/multi-worker